[package]
name = "seq-cmd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
device_query = "1.1.3"
crossbeam = "0.8.2"
chrono = "0.4.31"
